"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
""" 
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# ==============================================================================
# ENVIRONMENT UTILITY
# ==============================================================================
def get_env_variable(var_name, default=None, required=False):
    """
    Retrieve environment variables globally.
    If required=True and the variable is missing, it fails the startup securely.
    """
    try:
        return os.environ[var_name]
    except KeyError:
        if required:
            raise ImproperlyConfigured(f"CRITICAL SECURITY ERROR: Set the {var_name} environment variable.")
        return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR.parent, '.env')) # If .env is in Obsidian folder
load_dotenv(os.path.join(BASE_DIR, '.env'))        # Fallback if .env is in obsidian-backend folder

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY', required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable('DEBUG', default='False') == 'True'

ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost']
# CSRF_TRUSTED_ORIGINS is configured dynamically in the CORS section below
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'cloudinary',
  

    # Third-party Apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Local Apps
    'products',
    'orders',
    'users',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

db_url = os.environ.get('DATABASE_URL', '').strip()

if not db_url:
    # Fallback to local SQLite if DATABASE_URL is missing or empty
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Use Railway PostgreSQL Database in Production
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600
        )
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('es', 'Spanish'),
    ('en', 'English'),
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ==============================================================================
# URL to use when referring to static files
STATIC_URL = '/static/'

# Local directory where collectstatic will gather files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ==============================================================================
# MEDIA FILES & CLOUDINARY STORAGE (Product Images)
# ==============================================================================
# Base URL to serve media files
MEDIA_URL = '/media/'

# We DO NOT define MEDIA_ROOT here to prevent any local filesystem storage fallback!

# Cloudinary Credentials (ensure these variables are set in production)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': get_env_variable('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': get_env_variable('CLOUDINARY_API_KEY'),
    'API_SECRET': get_env_variable('CLOUDINARY_API_SECRET'),
}

# ==============================================================================
# STORAGE BACKENDS (Django 4.2+ Support)
# Django 5+ ignores DEFAULT_FILE_STORAGE. We must use the STORAGES dictionary.
# ==============================================================================
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.StaticFilesStorage",
    },
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Legacy Fallbacks (just in case)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==============================================================================
# CORS & CSRF CONFIGURATION
# ==============================================================================
# Parse dynamic comma-separated string from Railway environment
raw_origins = get_env_variable('CORS_ALLOWED_ORIGINS', default='')
parsed_origins = [origin.strip() for origin in raw_origins.split(',') if origin.strip()]

# Always guarantee local Vercel/Vite endpoints work safely
local_fallbacks = ['http://localhost:5173', 'http://127.0.0.1:5173']
final_origins = list(set(parsed_origins + local_fallbacks))

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = final_origins
CSRF_TRUSTED_ORIGINS = final_origins

# Vercel dynamic preview regex resolver
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://obsidian-.*\.vercel\.app$",
]

# ==============================================================================
# DJANGO REST FRAMEWORK CONFIGURATION
# ==============================================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# ==============================================================================
# SIMPLE JWT CONFIGURATION
# ==============================================================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# ==============================================================================
# EMAIL/SMTP CONFIGURATION (Resend)
# ==============================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
# Using dynamic env abstraction for sensitive API keys.
EMAIL_HOST_PASSWORD = get_env_variable('RESEND_API_KEY', required=True)
DEFAULT_FROM_EMAIL = 'onboarding@resend.dev'

# Python SDK Wrapper Alias
RESEND_API_KEY = EMAIL_HOST_PASSWORD

# ==============================================================================
# STRIPE CONFIGURATION
# ==============================================================================
STRIPE_PUBLIC_KEY = get_env_variable('STRIPE_PUBLIC_KEY', required=True)
STRIPE_SECRET_KEY = get_env_variable('STRIPE_SECRET_KEY', required=True)

# Database persistence test.