# Generated by Django 6.0.3 on 2026-03-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='glove',
            name='collection_type',
            field=models.CharField(choices=[('DROP', 'Limited Edition'), ('CORE', 'Standard Item')], default='DROP', max_length=4),
        ),
        migrations.AlterField(
            model_name='glove',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='glove',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gloves', to='products.category'),
        ),
    ]
