# Generated by Django 6.0.3 on 2026-03-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glove',
            name='image',
        ),
    ]
