# Generated by Django 6.0.3 on 2026-04-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_glove_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='glove',
            name='countdown_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='is_featured_drop',
            field=models.BooleanField(default=False),
        ),
    ]
