# Generated by Django 6.0.3 on 2026-04-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_glove_countdown_end_glove_is_featured_drop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glove',
            old_name='countdown_end',
            new_name='countdown_target_date',
        ),
        migrations.RenameField(
            model_name='glove',
            old_name='is_featured_drop',
            new_name='is_hero_drop',
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_marketing_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_title_over_the_product',
            field=models.CharField(blank=True, help_text='e.g., LA SEGUNDA PIEL. LOTE 001.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='limited_drop_info_text',
            field=models.CharField(blank=True, help_text='e.g., Strictly limited to 50 pairs.', max_length=100, null=True),
        ),
    ]
