# Generated by Django 6.0.3 on 2026-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_countdown_end_glove_countdown_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glove',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_marketing_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_marketing_description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_title_over_the_product_en',
            field=models.CharField(blank=True, help_text='e.g., LA SEGUNDA PIEL. LOTE 001.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='hero_title_over_the_product_es',
            field=models.CharField(blank=True, help_text='e.g., LA SEGUNDA PIEL. LOTE 001.', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='glove',
            name='name_es',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
